// Generate a small set of cross-language Schnorr KAT vectors for the Aiken verifier.
// Re-runnable; deterministic.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  SCALAR_ORDER,
  generator,
  pointToBytes,
  scalarMul,
} from "../src/crypto/bls.js";
import { proveSchnorr, publicPoint } from "../src/crypto/schnorr.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "../..");

const hex = (b: Uint8Array): string =>
  Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");

type Case = {
  base_kind: "g" | "scaled";
  base_scalar: string; // hex of k where base = [k]·g (k=1 ⇒ generator)
  secret: string;
  ctx: string;
  base: string;
  u: string;
  t: string;
  z: string;
};

function makeCase(secret: bigint, baseScalar: bigint, ctx: Uint8Array): Case {
  const base = baseScalar === 1n ? generator() : scalarMul(baseScalar, generator());
  const u = publicPoint(base, secret);
  const proof = proveSchnorr(base, secret, ctx);
  return {
    base_kind: baseScalar === 1n ? "g" : "scaled",
    base_scalar: baseScalar.toString(16),
    secret: secret.toString(16),
    ctx: hex(ctx),
    base: hex(pointToBytes(base)),
    u: hex(pointToBytes(u)),
    t: hex(proof.t),
    z: hex(proof.z),
  };
}

function buildCases(): Case[] {
  const cases: Case[] = [];
  // Spread of secrets and bases; vanilla generator + custom base for the Owner branch shape.
  const secrets = [1n, 2n, 7n, 0xdeadbeefn, SCALAR_ORDER - 1n];
  const baseScalars = [1n, 7n];
  const ctxs = [
    new Uint8Array(0),
    new TextEncoder().encode("ctx"),
    new Uint8Array(64).fill(0xa5),
  ];
  for (const x of secrets) {
    for (const k of baseScalars) {
      for (const ctx of ctxs) {
        cases.push(makeCase(x, k, ctx));
      }
    }
  }
  return cases;
}

function emitJson(cases: Case[], path: string) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(cases, null, 2) + "\n");
}

function aikenLit(h: string): string {
  return h.length === 0 ? `#""` : `#"${h}"`;
}

function emitAiken(cases: Case[], path: string) {
  const tests = cases
    .map(
      (c, i) => `test schnorr_kat_${i}() {
  schnorr.verify(
    ${aikenLit(c.base)},
    ${aikenLit(c.u)},
    schnorr.SchnorrProof { t: ${aikenLit(c.t)}, z: ${aikenLit(c.z)} },
    ${aikenLit(c.ctx)},
  )
}`,
    )
    .join("\n\n");

  const negatives = cases
    .map(
      (c, i) => `test schnorr_kat_neg_z_flip_${i}() fail {
  // Flip the LSB of z — proof must be rejected.
  let z_bad: ByteArray = ${aikenLit(flipByte(c.z, c.z.length / 2 - 2))}
  schnorr.verify(
    ${aikenLit(c.base)},
    ${aikenLit(c.u)},
    schnorr.SchnorrProof { t: ${aikenLit(c.t)}, z: z_bad },
    ${aikenLit(c.ctx)},
  )
}`,
    )
    .join("\n\n");

  const out = `//// AUTO-GENERATED by offchain/scripts/gen-schnorr-kat.ts. Do NOT edit by hand.
//// Re-run \`pnpm --filter @lovejoin/sdk run gen:schnorr-kat\` to refresh.

use lovejoin/schnorr

${tests}

${negatives}
`;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, out);
}

function flipByte(hex: string, bytePos: number): string {
  const bytesArr = hex.match(/../g) ?? [];
  const idx = Math.max(0, Math.min(bytePos, bytesArr.length - 1));
  const v = parseInt(bytesArr[idx]!, 16) ^ 0x01;
  bytesArr[idx] = v.toString(16).padStart(2, "0");
  return bytesArr.join("");
}

const cases = buildCases();
const jsonPath = resolve(REPO_ROOT, "crypto/test-vectors/provedlog.json");
const aikenPath = resolve(REPO_ROOT, "contracts/lib/lovejoin/schnorr_kat.test.ak");
emitJson(cases, jsonPath);
emitAiken(cases, aikenPath);
console.log(`wrote ${cases.length} Schnorr KAT cases to ${jsonPath}`);
console.log(`wrote ${cases.length * 2} Aiken Schnorr tests to ${aikenPath}`);
