// Generate cross-language DHTuple KAT vectors. Re-runnable; deterministic.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { SCALAR_ORDER, generator, pointToBytes, scalarMul } from "../src/crypto/bls.js";
import { dhPair, proveDHTuple } from "../src/crypto/dhtuple.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "../..");

const hex = (b: Uint8Array): string =>
  Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");

type Case = {
  g_scalar: string;
  h_scalar: string;
  secret: string;
  ctx: string;
  g: string;
  h: string;
  u: string;
  v: string;
  t0: string;
  t1: string;
  z: string;
};

function makeCase(secret: bigint, gScalar: bigint, hScalar: bigint, ctx: Uint8Array): Case {
  const g = gScalar === 1n ? generator() : scalarMul(gScalar, generator());
  const h = hScalar === 1n ? generator() : scalarMul(hScalar, generator());
  const { u, v } = dhPair(g, h, secret);
  const proof = proveDHTuple(g, h, secret, ctx);
  return {
    g_scalar: gScalar.toString(16),
    h_scalar: hScalar.toString(16),
    secret: secret.toString(16),
    ctx: hex(ctx),
    g: hex(pointToBytes(g)),
    h: hex(pointToBytes(h)),
    u: hex(pointToBytes(u)),
    v: hex(pointToBytes(v)),
    t0: hex(proof.t0),
    t1: hex(proof.t1),
    z: hex(proof.z),
  };
}

function buildCases(): Case[] {
  const cases: Case[] = [];
  // Mirror of the Mix-branch shape: g and h are box's (a, b), arbitrary independent points.
  const ghPairs: Array<[bigint, bigint]> = [
    [3n, 5n],
    [11n, 13n],
    [0xa1n, 0xb1n],
  ];
  const secrets = [1n, 7n, 0xdeadbeefn, SCALAR_ORDER - 1n];
  const ctxs = [new Uint8Array(0), new TextEncoder().encode("ctx"), new Uint8Array(64).fill(0xa5)];
  for (const [gK, hK] of ghPairs) {
    for (const x of secrets) {
      for (const ctx of ctxs) {
        cases.push(makeCase(x, gK, hK, ctx));
      }
    }
  }
  return cases;
}

function aikenLit(h: string): string {
  return h.length === 0 ? `#""` : `#"${h}"`;
}

function emitAiken(cases: Case[], path: string) {
  const positives = cases
    .map(
      (c, i) => `test dhtuple_kat_${i}() {
  dhtuple.verify(
    ${aikenLit(c.g)},
    ${aikenLit(c.h)},
    ${aikenLit(c.u)},
    ${aikenLit(c.v)},
    dhtuple.DHTupleProof { t0: ${aikenLit(c.t0)}, t1: ${aikenLit(c.t1)}, z: ${aikenLit(c.z)} },
    ${aikenLit(c.ctx)},
  )
}`,
    )
    .join("\n\n");

  const negativesT0 = cases
    .map((c, i) => {
      const tampered = flipByte(c.t0, 8);
      return `test dhtuple_kat_neg_t0_flip_${i}() fail {
  dhtuple.verify(
    ${aikenLit(c.g)},
    ${aikenLit(c.h)},
    ${aikenLit(c.u)},
    ${aikenLit(c.v)},
    dhtuple.DHTupleProof { t0: ${aikenLit(tampered)}, t1: ${aikenLit(c.t1)}, z: ${aikenLit(c.z)} },
    ${aikenLit(c.ctx)},
  )
}`;
    })
    .join("\n\n");

  const negativesV = cases
    .map((c, i) => {
      const tampered = flipByte(c.v, 8);
      return `test dhtuple_kat_neg_v_flip_${i}() fail {
  dhtuple.verify(
    ${aikenLit(c.g)},
    ${aikenLit(c.h)},
    ${aikenLit(c.u)},
    ${aikenLit(tampered)},
    dhtuple.DHTupleProof { t0: ${aikenLit(c.t0)}, t1: ${aikenLit(c.t1)}, z: ${aikenLit(c.z)} },
    ${aikenLit(c.ctx)},
  )
}`;
    })
    .join("\n\n");

  const out = `//// AUTO-GENERATED by offchain/scripts/gen-dhtuple-kat.ts. Do NOT edit by hand.
//// Re-run \`pnpm --filter @lovejoin/sdk run gen:dhtuple-kat\` to refresh.

use lovejoin/dhtuple

${positives}

${negativesT0}

${negativesV}
`;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, out);
}

function flipByte(hex: string, bytePos: number): string {
  const arr = hex.match(/../g) ?? [];
  const idx = Math.max(0, Math.min(bytePos, arr.length - 1));
  const v = parseInt(arr[idx]!, 16) ^ 0x01;
  arr[idx] = v.toString(16).padStart(2, "0");
  return arr.join("");
}

const cases = buildCases();
const jsonPath = resolve(REPO_ROOT, "crypto/test-vectors/provedhtuple.json");
const aikenPath = resolve(REPO_ROOT, "contracts/lib/lovejoin/dhtuple_kat.test.ak");
mkdirSync(dirname(jsonPath), { recursive: true });
writeFileSync(jsonPath, JSON.stringify(cases, null, 2) + "\n");
emitAiken(cases, aikenPath);
console.log(`wrote ${cases.length} DHTuple KAT cases to ${jsonPath}`);
console.log(`wrote ${cases.length * 3} Aiken DHTuple tests to ${aikenPath}`);
