// Unit tests for backend/src/address.ts.
//
// backend/src/address.ts is an intentional copy of the SDK helper at
// offchain/src/tx/address.ts (the backend deliberately does not depend on
// `@lovejoin/sdk`). Reference vectors below are the same vectors the SDK
// test uses, so the two implementations stay byte-for-byte in lockstep.
//
// All addr_test… vectors below were generated by:
//   cardano-cli conway address build --payment-script-file <plutus> --testnet-magic 1
// from artifacts/preprod/*.plutus. If this hand-rolled bech32 ever drifts
// from cardano-cli, these tests fail loudly — and "diverges by one byte" is
// the kind of bug that silently routes funds to the wrong address.

import { describe, expect, it } from "vitest";

import { buildScriptAddress } from "../src/address.js";

// Known-good Preprod script hashes (from artifacts/preprod/addresses.json).
const FEE_CONTRACT = "5efd8fdd7e4d35b04de427337220dcb30352136d739055b305dd2d66";
const MIX_BOX = "ba176a7604f3e062a7ed315780801495ed0ffb0191c6f8e7d88362e2";
const REFERENCE_HOLDER = "b58b5869a956266f5a55265829963064cabfeac4dab3c28f46dbc1cc";
// dApp stake key from config/network.preprod.json.
const PREPROD_STAKE = "1e3105f23f2ac91b3fb4c35fa4fe301421028e356e114944e902005b";

describe("address — buildScriptAddress: enterprise (no stake)", () => {
  it("encodes a preprod fee_contract enterprise address", () => {
    expect(buildScriptAddress(FEE_CONTRACT, 0)).toBe(
      "addr_test1wp00mr7a0exntvzdusnnxu3qmjesx5snd4eeq4dnqhwj6esn2pdrd",
    );
  });

  it("encodes a preprod mix_box enterprise address", () => {
    expect(buildScriptAddress(MIX_BOX, 0)).toBe(
      "addr_test1wzapw6nkqne7qc48a5c40qyqzj276rlmqxgud788mzpk9csxv0enu",
    );
  });

  it("encodes a preprod reference_holder enterprise address", () => {
    expect(buildScriptAddress(REFERENCE_HOLDER, 0)).toBe(
      "addr_test1wz6ckkrf49tzvm6625n9s2vkxpjv40l2cndt8s50gmdurnqhmdez7",
    );
  });

  it("treats null and undefined stake credential as 'no stake'", () => {
    const enterprise = buildScriptAddress(FEE_CONTRACT, 0);
    expect(buildScriptAddress(FEE_CONTRACT, 0, null)).toBe(enterprise);
    expect(buildScriptAddress(FEE_CONTRACT, 0, undefined)).toBe(enterprise);
    expect(buildScriptAddress(FEE_CONTRACT, 0, "")).toBe(enterprise);
  });

  it("uses the mainnet HRP and header bit when networkId=1", () => {
    const out = buildScriptAddress(FEE_CONTRACT, 1);
    expect(out.startsWith("addr1")).toBe(true);
    // First data char encodes the high nibble of the header byte.
    // Type 0111 + network 1 = header 0x71 → first 5-bit group is 0b01110 = 14 → 'w'.
    expect(out.startsWith("addr1w")).toBe(true);
  });

  it("tolerates 0x prefix (case-insensitive) on input", () => {
    expect(buildScriptAddress(`0x${FEE_CONTRACT}`, 0)).toBe(buildScriptAddress(FEE_CONTRACT, 0));
    expect(buildScriptAddress(`0X${FEE_CONTRACT}`, 0)).toBe(buildScriptAddress(FEE_CONTRACT, 0));
  });
});

describe("address — buildScriptAddress: base (script + stake)", () => {
  it("emits an addr_test1z… base address on testnet when stake hash is set", () => {
    const out = buildScriptAddress(FEE_CONTRACT, 0, PREPROD_STAKE);
    // Type 0001 + network 0 = header 0x10 → first 5-bit group is 0b00010 = 2 → 'z'.
    expect(out.startsWith("addr_test1z")).toBe(true);
    expect(out).not.toBe(buildScriptAddress(FEE_CONTRACT, 0));
  });

  it("emits an addr1z… base address on mainnet when stake hash is set", () => {
    const mainnetStake = "07ac7dee6c82177096b70ccf21cfb8965c1fb08e079f9ca4af4b2b3e";
    const out = buildScriptAddress(FEE_CONTRACT, 1, mainnetStake);
    expect(out.startsWith("addr1z")).toBe(true);
  });

  it("changes the address when the stake hash changes", () => {
    const stakeA = "1e3105f23f2ac91b3fb4c35fa4fe301421028e356e114944e902005b";
    const stakeB = "07ac7dee6c82177096b70ccf21cfb8965c1fb08e079f9ca4af4b2b3e";
    expect(buildScriptAddress(FEE_CONTRACT, 0, stakeA)).not.toBe(
      buildScriptAddress(FEE_CONTRACT, 0, stakeB),
    );
  });
});

describe("address — buildScriptAddress: malformed input", () => {
  it("rejects script hashes that are too short", () => {
    expect(() => buildScriptAddress("ab".repeat(20), 0)).toThrow(
      /payment-script hash must be 28 bytes/,
    );
    expect(() => buildScriptAddress("", 0)).toThrow(/payment-script hash must be 28 bytes/);
  });

  it("rejects script hashes that are too long", () => {
    expect(() => buildScriptAddress("ab".repeat(32), 0)).toThrow(
      /payment-script hash must be 28 bytes/,
    );
    expect(() => buildScriptAddress("ab".repeat(64), 0)).toThrow(
      /payment-script hash must be 28 bytes/,
    );
  });

  it("rejects odd-length hex", () => {
    expect(() => buildScriptAddress("abc", 0)).toThrow(/even length/);
  });

  it("rejects non-hex characters", () => {
    // `gg` parses as NaN through Number.parseInt(_, 16).
    const bad = `gg${"ab".repeat(27)}`;
    expect(() => buildScriptAddress(bad, 0)).toThrow(/bad hex byte/);
  });

  it("rejects stake hashes with the wrong byte length", () => {
    expect(() => buildScriptAddress(FEE_CONTRACT, 0, "ab".repeat(20))).toThrow(
      /stake-key hash must be 28 bytes/,
    );
    expect(() => buildScriptAddress(FEE_CONTRACT, 0, "ab".repeat(32))).toThrow(
      /stake-key hash must be 28 bytes/,
    );
  });
});

describe("address — buildScriptAddress: round-trip and length", () => {
  it("round-trips: decoded enterprise payload yields the original script hash", () => {
    const out = buildScriptAddress(FEE_CONTRACT, 0);
    const { hrp, payload } = decodeBech32(out);
    expect(hrp).toBe("addr_test");
    expect(payload.length).toBe(29);
    expect((payload[0]! & 0xf0) >>> 0).toBe(0x70); // enterprise script header high nibble
    expect((payload[0]! & 0x0f) >>> 0).toBe(0); // network 0
    expect(bytesToHex(payload.slice(1))).toBe(FEE_CONTRACT);
  });

  it("round-trips: decoded base payload yields original script + stake hashes", () => {
    const out = buildScriptAddress(FEE_CONTRACT, 0, PREPROD_STAKE);
    const { hrp, payload } = decodeBech32(out);
    expect(hrp).toBe("addr_test");
    expect(payload.length).toBe(57);
    expect((payload[0]! & 0xf0) >>> 0).toBe(0x10); // base script+key header high nibble
    expect((payload[0]! & 0x0f) >>> 0).toBe(0); // network 0
    expect(bytesToHex(payload.slice(1, 29))).toBe(FEE_CONTRACT);
    expect(bytesToHex(payload.slice(29))).toBe(PREPROD_STAKE);
  });

  it("round-trips on mainnet too", () => {
    const out = buildScriptAddress(FEE_CONTRACT, 1);
    const { hrp, payload } = decodeBech32(out);
    expect(hrp).toBe("addr");
    expect((payload[0]! & 0x0f) >>> 0).toBe(1); // network 1
    expect(bytesToHex(payload.slice(1))).toBe(FEE_CONTRACT);
  });

  it("emits the canonical fixed lengths for enterprise and base on testnet", () => {
    // Enterprise: HRP "addr_test" (9) + "1" (1) + 47 data chars + 6 checksum = 63 chars.
    expect(buildScriptAddress(FEE_CONTRACT, 0).length).toBe(63);
    // Base: HRP "addr_test" (9) + "1" (1) + 92 data chars + 6 checksum = 108 chars.
    expect(buildScriptAddress(FEE_CONTRACT, 0, PREPROD_STAKE).length).toBe(108);
  });

  it("emits the canonical fixed lengths for enterprise and base on mainnet", () => {
    // HRP "addr" is 5 chars shorter than "addr_test", so each shrinks by 5.
    expect(buildScriptAddress(FEE_CONTRACT, 1).length).toBe(58);
    expect(buildScriptAddress(FEE_CONTRACT, 1, PREPROD_STAKE).length).toBe(103);
  });

  it("uses only the bech32 charset in the data + checksum portion", () => {
    const out = buildScriptAddress(FEE_CONTRACT, 0, PREPROD_STAKE);
    const sep = out.lastIndexOf("1");
    const dataPart = out.slice(sep + 1);
    // BIP-173 charset omits 'b','i','o' and digit '1' (the separator).
    expect(dataPart).toMatch(/^[ac-hj-np-z02-9]+$/);
  });
});

// ---------------------------------------------------------------------------
// Local bech32 *decoder* — test-only. The encoder under test ships without a
// matching decoder (it never needs one in production), so we inline a minimal
// reference here for the round-trip property. Direct port of BIP-173 §5.
// ---------------------------------------------------------------------------

const BECH32_CHARSET = "qpzry9x8gf2tvdw0s3jn54khce6mua7l";

function decodeBech32(s: string): { hrp: string; payload: Uint8Array } {
  const sep = s.lastIndexOf("1");
  if (sep < 1 || sep + 7 > s.length) throw new Error(`decodeBech32: bad separator in ${s}`);
  const hrp = s.slice(0, sep);
  const dataPart = s.slice(sep + 1);
  const data: number[] = [];
  for (const ch of dataPart) {
    const v = BECH32_CHARSET.indexOf(ch);
    if (v === -1) throw new Error(`decodeBech32: char ${ch} not in bech32 charset`);
    data.push(v);
  }
  if (bech32Polymod([...hrpExpand(hrp), ...data]) !== 1) {
    throw new Error(`decodeBech32: bad checksum on ${s}`);
  }
  const groups = data.slice(0, data.length - 6);
  const bytes = convertBits5to8(groups);
  return { hrp, payload: Uint8Array.from(bytes) };
}

function hrpExpand(hrp: string): number[] {
  const out: number[] = [];
  for (let i = 0; i < hrp.length; i++) out.push(hrp.charCodeAt(i) >> 5);
  out.push(0);
  for (let i = 0; i < hrp.length; i++) out.push(hrp.charCodeAt(i) & 0x1f);
  return out;
}

function bech32Polymod(values: number[]): number {
  const generator = [0x3b6a57b2, 0x26508e6d, 0x1ea119fa, 0x3d4233dd, 0x2a1462b3];
  let chk = 1;
  for (const v of values) {
    const top = chk >> 25;
    chk = ((chk & 0x1ffffff) << 5) ^ v;
    for (let i = 0; i < 5; i++) {
      if ((top >> i) & 1) chk ^= generator[i]!;
    }
  }
  return chk;
}

function convertBits5to8(data: number[]): number[] {
  let acc = 0;
  let bits = 0;
  const out: number[] = [];
  for (const v of data) {
    acc = (acc << 5) | v;
    bits += 5;
    if (bits >= 8) {
      bits -= 8;
      out.push((acc >> bits) & 0xff);
    }
  }
  // Trailing bits are zero-padding from the encoder; ignore.
  return out;
}

function bytesToHex(b: Uint8Array): string {
  let out = "";
  for (const x of b) out += x.toString(16).padStart(2, "0");
  return out;
}
