// Determinism + KAT tests for the wallet-derived seed flow.
//
// Spec: M6.5 vault rework. The whole point of wallet-derived owner secrets
// is that the *same* (wallet, payload) input always produces the *same*
// per-deposit `x_i`. We pin that property here at three layers:
//
//   1. `deriveSeedFromSignatureBytes` — same signature bytes → same 32-byte
//      seed. (blake2b_256 is deterministic, this is mostly a regression
//      net for accidental refactors.)
//   2. `deriveOwnerSecret` — same seed + same index → byte-identical
//      scalar. Different indices → different scalars (high probability).
//   3. `deriveSeedFromWalletSignature` — same stub wallet signData output
//      → same seed. The mocked wallet returns a fixed signature, so this
//      is really an end-to-end pin of the round-trip.
//
// We also assert the failure modes spelled out in the implementation: empty
// signature, out-of-range index, wrong-length seed.

import { describe, expect, it } from "vitest";

import {
  SCALAR_ORDER,
  scalarToBytes,
} from "../../src/crypto/bls.js";
import {
  SIGN_DATA_PAYLOAD_V1,
  deriveOwnerSecret,
  deriveSeedFromSignatureBytes,
  deriveSeedFromSignatureHex,
  deriveSeedFromWalletSignature,
  type SignDataCapableWallet,
} from "../../src/wallet/seed.js";

// A fake CIP-8 envelope hex — meaningful only as a stable input to the
// hash. Real envelopes are 100+ bytes; this is short for test legibility.
const FIXED_SIG_HEX =
  "84a4012704581d61bb176a7604f3e062a7ed315780801495ed0ffb0191c6f8e7d88362e2" +
  "8000a166686173686564f4581b6c6f76656a6f696e2f6f776e65722f7631";

describe("deriveSeedFromSignatureBytes", () => {
  it("produces a 32-byte seed from non-empty signature bytes", () => {
    const seed = deriveSeedFromSignatureBytes(new Uint8Array([1, 2, 3, 4]));
    expect(seed).toBeInstanceOf(Uint8Array);
    expect(seed.length).toBe(32);
  });

  it("is deterministic across repeated calls with the same input", () => {
    const sig = new Uint8Array([0xab, 0xcd, 0xef]);
    const a = deriveSeedFromSignatureBytes(sig);
    const b = deriveSeedFromSignatureBytes(sig);
    expect(a).toEqual(b);
  });

  it("changes when even one byte of the signature changes", () => {
    const a = deriveSeedFromSignatureBytes(new Uint8Array([1, 2, 3]));
    const b = deriveSeedFromSignatureBytes(new Uint8Array([1, 2, 4]));
    expect(a).not.toEqual(b);
  });

  it("rejects an empty signature", () => {
    expect(() => deriveSeedFromSignatureBytes(new Uint8Array(0))).toThrow(
      /non-empty/,
    );
  });
});

describe("deriveSeedFromSignatureHex", () => {
  it("matches deriveSeedFromSignatureBytes on the same hex round-trip", () => {
    const hex = "deadbeef0001";
    const fromHex = deriveSeedFromSignatureHex(hex);
    const fromBytes = deriveSeedFromSignatureBytes(
      Uint8Array.from(Buffer.from(hex, "hex")),
    );
    expect(fromHex).toEqual(fromBytes);
  });

  it("accepts a 0x-prefixed hex string the same as the bare form", () => {
    const a = deriveSeedFromSignatureHex(FIXED_SIG_HEX);
    const b = deriveSeedFromSignatureHex(`0x${FIXED_SIG_HEX}`);
    expect(a).toEqual(b);
  });
});

describe("deriveOwnerSecret", () => {
  const seed = deriveSeedFromSignatureHex(FIXED_SIG_HEX);

  it("returns a non-zero scalar strictly less than r", () => {
    const x = deriveOwnerSecret(seed, 0);
    expect(x).toBeGreaterThan(0n);
    expect(x).toBeLessThan(SCALAR_ORDER);
  });

  it("is deterministic across repeated calls with the same (seed, index)", () => {
    const a = deriveOwnerSecret(seed, 7);
    const b = deriveOwnerSecret(seed, 7);
    expect(scalarToBytes(a)).toEqual(scalarToBytes(b));
  });

  it("returns distinct secrets for distinct indices (sampled)", () => {
    const xs = [0, 1, 2, 3, 7, 100, 65535, 0xfffffffe].map((i) =>
      scalarToBytes(deriveOwnerSecret(seed, i)),
    );
    const set = new Set(xs.map((b) => Buffer.from(b).toString("hex")));
    expect(set.size).toBe(xs.length);
  });

  it("rejects a wrong-length seed", () => {
    expect(() =>
      deriveOwnerSecret(new Uint8Array(31), 0),
    ).toThrow(/32 bytes/);
    expect(() =>
      deriveOwnerSecret(new Uint8Array(33), 0),
    ).toThrow(/32 bytes/);
  });

  it("rejects negative or non-uint32 indices", () => {
    expect(() => deriveOwnerSecret(seed, -1)).toThrow(/uint32/);
    expect(() => deriveOwnerSecret(seed, 1.5)).toThrow(/uint32/);
    expect(() => deriveOwnerSecret(seed, 0x1_0000_0000)).toThrow(/uint32/);
  });

  it("pins a known answer at index 0 for the fixture signature (KAT)", () => {
    // The exact byte vector below is regenerated by the implementation
    // every time the test runs — we capture it here so a future refactor
    // that changes HKDF info bytes / domain tag fails loudly instead of
    // silently invalidating every existing user's deposits.
    const x = deriveOwnerSecret(seed, 0);
    const hex = Buffer.from(scalarToBytes(x)).toString("hex");
    expect(hex).toMatch(/^[0-9a-f]{64}$/);
    // KAT — pinned from a reference run; bumps are deliberate.
    expect(hex).toBe(
      "35045fcfd4a128dee2a054463c39a90dad1e9393336ba311da6b1f53bb3ee867",
    );
  });
});

describe("deriveSeedFromWalletSignature", () => {
  // Mesh's BrowserWallet.signData(payload, address) — payload first,
  // address second, plain UTF-8 payload (mesh hex-encodes internally).
  // The fakeWallet mirrors that contract exactly.
  function fakeWallet(
    handler: (payload: string, address?: string) => Promise<{ signature: string; key: string }>,
    rewardAddrs: string[] = ["stake_test1u_dummy"],
  ): SignDataCapableWallet {
    return {
      signData: handler,
      getRewardAddresses: async () => rewardAddrs,
    };
  }

  it("calls signData with the v1 payload + first reward address by default", async () => {
    let lastAddr = "";
    let lastPayload = "";
    const wallet = fakeWallet(async (payload, address) => {
      lastAddr = address ?? "";
      lastPayload = payload;
      return { signature: FIXED_SIG_HEX, key: "00" };
    });
    const out = await deriveSeedFromWalletSignature({ wallet });
    expect(lastAddr).toBe("stake_test1u_dummy");
    // Mesh wants plain UTF-8 — not hex — and handles encoding internally.
    expect(lastPayload).toBe(SIGN_DATA_PAYLOAD_V1);
    expect(out.signatureHex).toBe(FIXED_SIG_HEX);
    expect(out.address).toBe("stake_test1u_dummy");
  });

  it("returns a seed identical to deriveSeedFromSignatureHex on the same signature", async () => {
    const wallet = fakeWallet(async () => ({ signature: FIXED_SIG_HEX, key: "00" }));
    const direct = deriveSeedFromSignatureHex(FIXED_SIG_HEX);
    const indirect = await deriveSeedFromWalletSignature({ wallet });
    expect(indirect.seed).toEqual(direct);
  });

  it("uses a caller-supplied stake address override", async () => {
    let seenAddr = "";
    const wallet = fakeWallet(async (_payload, address) => {
      seenAddr = address ?? "";
      return { signature: FIXED_SIG_HEX, key: "00" };
    });
    await deriveSeedFromWalletSignature({
      wallet,
      stakeAddrBech32: "stake_test1uOVERRIDE",
    });
    expect(seenAddr).toBe("stake_test1uOVERRIDE");
  });

  it("throws clearly when the wallet exposes no reward address", async () => {
    const wallet = fakeWallet(
      async () => ({ signature: FIXED_SIG_HEX, key: "00" }),
      [],
    );
    await expect(deriveSeedFromWalletSignature({ wallet })).rejects.toThrow(
      /reward .*addresses/i,
    );
  });
});
