// SDK bridge — wires @lovejoin/sdk into the React app.
//
// Spec: M3.5 vertical slice (docs/spec/12-build-guide.md
// §"The thin happy-path slice"). The UI exercises the M3 SDK with a real
// CIP-30 browser wallet so we surface mesh + libsodium + bundling issues
// before going deep on M4's Mix builder.
//
// What this module owns:
//   * Loading addresses.json (the bootstrap output) over fetch — committed
//     copy lives in ui/public/addresses.preprod.json.
//   * Persisting per-user runtime config (Blockfrost project id, network)
//     in localStorage so reloads don't lose the dev's key.
//   * Constructing the BlockfrostProvider on demand.
//   * Providing a BrowserWallet helper that survives the lazy mesh import.
//
// What this module deliberately does NOT own: any tx-builder logic. Deposit
// + withdraw screens call into the SDK's `buildDepositTx` / `buildWithdrawTx`
// directly with the wallet handle and provider that this bridge produces.

import { BlockfrostProvider, type LovejoinAddresses } from "@lovejoin/sdk";

export const NETWORKS = ["preprod", "preview", "mainnet"] as const;
export type Network = (typeof NETWORKS)[number];

const STORAGE_KEY = "lovejoin.config.v1";

const DEFAULT_COLLATERAL_PROVIDER_ENDPOINT = "https://giveme.my";

/**
 * Persisted-across-reloads runtime configuration.
 *
 * `backendUrl` is optional — the M5 indexer is a deployment choice, not a
 * hard dep. When set, the Pool screen reads pool size + indexer lag from it;
 * when unset, the screen falls back to direct Blockfrost queries.
 *
 * `collateralProviderEndpoint` defaults to giveme.my (the canonical service
 * called out in docs/spec/01-protocol.md §"Collateral provider"). Operators
 * running their own provider override it.
 */
export interface RuntimeConfig {
  network: Network;
  blockfrostProjectId: string;
  backendUrl: string;
  collateralProviderEndpoint: string;
}

export const DEFAULT_CONFIG: RuntimeConfig = {
  network: "preprod",
  blockfrostProjectId: "",
  backendUrl: "",
  collateralProviderEndpoint: DEFAULT_COLLATERAL_PROVIDER_ENDPOINT,
};

export function loadConfig(): RuntimeConfig {
  if (typeof window === "undefined") return DEFAULT_CONFIG;
  try {
    const raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) return DEFAULT_CONFIG;
    const parsed = JSON.parse(raw) as Partial<RuntimeConfig>;
    const network = NETWORKS.includes(parsed.network as Network)
      ? (parsed.network as Network)
      : DEFAULT_CONFIG.network;
    return {
      network,
      blockfrostProjectId: parsed.blockfrostProjectId ?? "",
      backendUrl: parsed.backendUrl ?? "",
      collateralProviderEndpoint:
        parsed.collateralProviderEndpoint?.trim() ||
        DEFAULT_COLLATERAL_PROVIDER_ENDPOINT,
    };
  } catch {
    return DEFAULT_CONFIG;
  }
}

export function saveConfig(cfg: RuntimeConfig): void {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(STORAGE_KEY, JSON.stringify(cfg));
}

/**
 * Map a network name to the Blockfrost API base URL. Mirrors the SDK CLI
 * (offchain/src/cli/index.ts) so a project id that works on the CLI works
 * here unchanged.
 */
export function blockfrostBaseUrl(network: Network): string {
  if (network === "mainnet") return "https://cardano-mainnet.blockfrost.io/api/v0";
  if (network === "preview") return "https://cardano-preview.blockfrost.io/api/v0";
  return "https://cardano-preprod.blockfrost.io/api/v0";
}

/**
 * Build a chain provider for the given runtime config. Throws if no project
 * id has been entered — surfaces the empty-config case loudly rather than
 * letting Blockfrost reject the request later with a 403.
 */
export function makeProvider(cfg: RuntimeConfig): BlockfrostProvider {
  if (!cfg.blockfrostProjectId.trim()) {
    throw new Error("Blockfrost project ID required — open the config panel.");
  }
  return new BlockfrostProvider({
    baseUrl: blockfrostBaseUrl(cfg.network),
    projectId: cfg.blockfrostProjectId.trim(),
  });
}

/**
 * Fetch the bootstrap addresses.json for the given network. The file is a
 * static asset under ui/public/addresses.<network>.json copied from
 * artifacts/<network>/addresses.json by the developer running M3.5.
 *
 * Why fetch instead of import: the file is generated by the bootstrap
 * ceremony and not always present at typecheck time. A runtime fetch keeps
 * the build self-contained and lets the dev swap in a different network's
 * addresses without rebuilding.
 */
export async function loadAddresses(
  network: Network,
): Promise<LovejoinAddresses> {
  const url = `${import.meta.env.BASE_URL}addresses.${network}.json`;
  const res = await fetch(url, { cache: "no-cache" });
  if (!res.ok) {
    throw new Error(
      `addresses.${network}.json not found at ${url} (HTTP ${res.status}). ` +
        `Copy artifacts/${network}/addresses.json into ui/public/.`,
    );
  }
  return (await res.json()) as LovejoinAddresses;
}

/**
 * Mesh's BrowserWallet picker — returns the list of CIP-30 wallets the
 * browser has injected into `window.cardano`.
 *
 * The mesh import is lazy because @meshsdk/core transitively pulls
 * libsodium-wrappers-sumo, which fails to load in some environments
 * (see offchain/src/wallet/cip30.ts for the canonical writeup). The lazy
 * import means the rest of the UI renders even if mesh fails to initialize.
 */
export async function listInstalledWallets(): Promise<
  Array<{ id: string; name: string; icon: string; version: string }>
> {
  const { BrowserWallet } = await import("@meshsdk/core");
  return BrowserWallet.getInstalledWallets();
}

/**
 * Connect to a CIP-30 wallet by its id (e.g. "lace", "eternl", "nami") and
 * return the wallet handle the SDK tx builders accept.
 *
 * The result is structurally compatible with `LovejoinWallet` — the
 * minimum surface the tx builders need. We don't widen the return type to
 * `LovejoinWallet` here because consumers may want the full BrowserWallet
 * (e.g. `getBalance`, `getNetworkId`) for diagnostics.
 */
export async function connectWallet(
  id: string,
): Promise<import("@meshsdk/core").BrowserWallet> {
  const { BrowserWallet } = await import("@meshsdk/core");
  return BrowserWallet.enable(id);
}
