// bech32 decoder tests — focused on the Cardano addresses the Withdraw
// screen will see.

import { describe, expect, it } from "vitest";

import { bech32Decode } from "../src/lib/bech32.js";

// A round-trip-tested vector — generated by the SDK's buildScriptAddress
// for the canonical Preprod mix-box script hash, no stake key. Kept here
// rather than calling the SDK builder at test time so a regression in this
// decoder surfaces independently of the SDK's encoder.
const VALID_ADDR =
  "addr_test1wzapw6nkqne7qc48a5c40qyqzj276rlmqxgud788mzpk9csxv0enu";

describe("bech32Decode", () => {
  it("decodes a valid testnet enterprise-script address", () => {
    const decoded = bech32Decode(VALID_ADDR);
    expect(decoded).not.toBeNull();
    expect(decoded!.hrp).toBe("addr_test");
    expect((decoded!.bytes[0]! >> 4) & 0xf).toBe(0x7); // enterprise-script
  });

  it("rejects mixed case", () => {
    const mixed = VALID_ADDR.replace(/^a/, "A");
    expect(bech32Decode(mixed)).toBeNull();
  });

  it("rejects bad checksum", () => {
    // Flip the last char to a different valid bech32 char — alphabet ok,
    // checksum broken.
    const tampered = VALID_ADDR.slice(0, -1) + (VALID_ADDR.endsWith("u") ? "v" : "u");
    expect(bech32Decode(tampered)).toBeNull();
  });

  it("rejects strings that are too short", () => {
    expect(bech32Decode("a1bc")).toBeNull();
  });

  it("rejects characters outside the charset", () => {
    // 'b' is a valid bech32 char; '8' isn't in the position we hijack.
    expect(bech32Decode("addr_test1bbbbbB")).toBeNull();
  });
});
