name = "logical-mechanism/lovejoin"
version = "0.1.0"
compiler = "v1.1.21"
plutus = "v3"
license = "MIT"
description = "Lovejoin — Sigmajoin privacy mixer on Cardano"

[repository]
user = "logical-mechanism"
project = "lovejoin"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"

[config]
