import { describe, expect, it } from "vitest";
import { SCALAR_ORDER, scalarToBytes } from "../../src/crypto/bls.js";
import { deriveNonce } from "../../src/crypto/nonce.js";

const hex = (b: Uint8Array): string =>
  Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");
const bytes = (s: string): Uint8Array =>
  s.length === 0 ? new Uint8Array(0) : new Uint8Array(Buffer.from(s, "hex"));

describe("crypto/nonce — RFC 6979 deterministic derivation", () => {
  it("returns a scalar in [1, r)", () => {
    const k = deriveNonce(0x1234n, bytes("aabbccdd"));
    expect(k > 0n).toBe(true);
    expect(k < SCALAR_ORDER).toBe(true);
  });

  it("rejects secrets outside [1, r)", () => {
    expect(() => deriveNonce(0n, new Uint8Array(0))).toThrow();
    expect(() => deriveNonce(SCALAR_ORDER, new Uint8Array(0))).toThrow();
    expect(() => deriveNonce(SCALAR_ORDER + 1n, new Uint8Array(0))).toThrow();
    expect(() => deriveNonce(-1n, new Uint8Array(0))).toThrow();
  });

  it("is deterministic: same (x, msg) ⇒ same scalar", () => {
    const x = 0xdeadbeef_cafef00dn;
    const msg = bytes("00010203040506070809");
    const k1 = deriveNonce(x, msg);
    const k2 = deriveNonce(x, msg);
    expect(k1).toBe(k2);
    expect(hex(scalarToBytes(k1))).toBe(hex(scalarToBytes(k2)));
  });

  it("differs across distinct messages with the same secret", () => {
    const x = 0x42n;
    const k1 = deriveNonce(x, bytes("01"));
    const k2 = deriveNonce(x, bytes("02"));
    expect(k1).not.toBe(k2);
  });

  it("differs across distinct secrets with the same message", () => {
    const msg = bytes("aa");
    const k1 = deriveNonce(0x42n, msg);
    const k2 = deriveNonce(0x43n, msg);
    expect(k1).not.toBe(k2);
  });

  it("is stable across a wide spread of (x, msg) inputs (regression-pin)", () => {
    // Pin actual derivation outputs so a refactor (e.g. swapping the underlying HMAC
    // library) cannot silently change them. Generated by this same code; if any of
    // these change, KAT vectors must be regenerated and downstream consumers
    // re-verified end-to-end.
    const cases: Array<{ x: bigint; msg: string; expected: string }> = [
      {
        x: 1n,
        msg: "",
        expected:
          "484e4ea71cfd582c0ae5aa71900ae5168453317f34cd85910727a5bb78972a95",
      },
      {
        x: 2n,
        msg: "00",
        expected:
          "20ed3145641ec58c7e2abca3d36fe429fc3667d7e300390c554e690e3e15f5ce",
      },
      {
        x: 0xffffffff_ffffffffn,
        msg: "deadbeef",
        expected:
          "4dd5f82a82d649423803ee6c5bcda28019bdd33b4b0813cecad49f78203d159e",
      },
      {
        x: SCALAR_ORDER - 1n,
        msg: "lovejoin",
        expected:
          "2309914cefda8343c5586566758e381459132584b3f2360af4e3ae8104bc22f6",
      },
    ];
    for (const c of cases) {
      const k = deriveNonce(c.x, bytes(c.msg));
      expect(hex(scalarToBytes(k))).toBe(c.expected);
    }
  });
});
